POST http://localhost:3001/api/trade
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWQiOiI2NDFjOTMyYjBiZGQyZWVlNzkwNWM1NGYiLCJpYXQiOjE2Nzk1OTkwNjEsImV4cCI6MTY4MjE5MTA2MX0.GDBw1jzUHlGjHRcPJn265WfE2-um1gcruuMEVvblTEA

{
    "senderId" : "641c932b0bdd2eee7905c54f",
    "receiverId" : "641c93970bdd2eee7905c573",
    "senderFakemonId" : "641c97dc00ad8cf33eab9765",
    "receiverFakemonId" : "641c97f600ad8cf33eab9782"
}

